import type {
  CalculatorField,
  CalculatorTemplate,
  CalculatorType,
  FormulaMode,
} from '../../shared/types/calculator';
import { createRandomId } from '../../shared/randomId';
import { createDefaultRequestFormSettings, createTemplatePublicId } from './model';

export type TemplateCatalogCategory =
  | 'business'
  | 'finance'
  | 'construction'
  | 'services'
  | 'other';

export interface TemplateCatalogPreset {
  id: string;
  title: string;
  description: string;
  usesCount: number;
  category: TemplateCatalogCategory;
  industry: string;
  audience: string;
  difficulty: 'quick' | 'medium' | 'advanced';
  estimatedSetup: string;
  recommendedFor: string;
  tags: string[];
  outcomes: string[];
  visual:
    | 'ceiling'
    | 'stretch'
    | 'repair'
    | 'delivery'
    | 'cleaning'
    | 'mortgage'
    | 'credit'
    | 'windows'
    | 'kitchen'
    | 'furniture'
    | 'beauty'
    | 'legal'
    | 'auto'
    | 'education'
    | 'events'
    | 'security'
    | 'septic'
    | 'fence';
  type: CalculatorType;
  basePrice: number;
  minPrice: number;
  globalCoefficient: number;
  discount: number;
  formulaMode: FormulaMode;
  customFormula: string;
  fields: CalculatorField[];
}

const numberField = (
  key: string,
  label: string,
  unitPrice: number,
  required = true,
  placeholder = 'Введите значение',
): CalculatorField => ({
  id: createRandomId(),
  key,
  label,
  type: 'number',
  required,
  unitPrice,
  coefficient: 1,
  placeholder,
});

const selectField = (
  key: string,
  label: string,
  options: Array<{ label: string; value: number; description?: string }>,
  placeholder = 'Выберите значение',
): CalculatorField => ({
  id: createRandomId(),
  key,
  label,
  type: 'select',
  required: true,
  unitPrice: 0,
  coefficient: 1,
  placeholder,
  showOptionPrices: true,
  useValueInFormula: true,
  options: options.map((option) => ({
    id: createRandomId(),
    ...option,
  })),
});

const checkboxField = (
  key: string,
  label: string,
  unitPrice: number,
  placeholder = 'Включить опцию',
): CalculatorField => ({
  id: createRandomId(),
  key,
  label,
  type: 'checkbox',
  required: false,
  unitPrice: 0,
  coefficient: 1,
  placeholder,
  checkboxLabel: label,
  onValue: unitPrice,
  offValue: 0,
  defaultValue: false,
  showPriceInline: true,
});

export const templateCatalog: TemplateCatalogPreset[] = [
  {
    id: 'ceilings',
    title: 'Натяжные потолки',
    description:
      'Расчет по площади, фактуре, освещению и скрытому карнизу. Хороший базовый шаблон для замерщиков и продажи выезда.',
    usesCount: 118,
    category: 'construction',
    industry: 'Потолки',
    audience: 'Замерщик и менеджер',
    difficulty: 'quick',
    estimatedSetup: '7 минут',
    recommendedFor: 'Быстрый лид-магнит',
    tags: ['потолки', 'натяжные', 'светильники', 'карниз'],
    outcomes: ['Площадь', 'Фактура', 'Свет'],
    visual: 'ceiling',
    type: 'construction',
    basePrice: 12000,
    minPrice: 18000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('area', 'Площадь, м²', 950),
      selectField('texture', 'Фактура', [
        { label: 'Матовая', value: 0, description: 'Классическое решение' },
        { label: 'Сатиновая', value: 3500, description: 'Мягкий благородный блеск' },
        { label: 'Глянцевая', value: 5200, description: 'Больше отражения и света' },
      ]),
      numberField('lights', 'Светильники, шт', 650, false),
      checkboxField('cornice', 'Скрытый карниз', 4800),
    ],
  },
  {
    id: 'stretch-light-lines',
    title: 'Парящие потолки с линиями света',
    description:
      'Нишевая сборка под премиальные проекты: полотно, световые линии, углы, ниша и подсветка.',
    usesCount: 137,
    category: 'construction',
    industry: 'Премиум-потолки',
    audience: 'Дизайнер и отдел продаж',
    difficulty: 'medium',
    estimatedSetup: '10 минут',
    recommendedFor: 'Апсейл среднего чека',
    tags: ['парящий потолок', 'световые линии', 'премиум'],
    outcomes: ['Линии света', 'Углы', 'Подсветка'],
    visual: 'stretch',
    type: 'construction',
    basePrice: 15000,
    minPrice: 22000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('area', 'Площадь, м²', 1100),
      selectField('canvasType', 'Тип полотна', [
        { label: 'Белое ПВХ', value: 0, description: 'Самый популярный вариант' },
        { label: 'Тканевое', value: 7200, description: 'Премиум-фактура без швов' },
        { label: 'Парящий потолок', value: 9800, description: 'С подсветкой по периметру' },
      ]),
      numberField('lightLines', 'Световые линии, м', 2200, false),
      numberField('angles', 'Доп. углы, шт', 350, false),
      checkboxField('lighting', 'Контурная подсветка', 8900),
    ],
  },
  {
    id: 'repair-flat',
    title: 'Ремонт квартир',
    description:
      'Смета по площади, уровню отделки и материалам. Подходит для быстрой первичной оценки в сообщении сообщества.',
    usesCount: 125,
    category: 'construction',
    industry: 'Ремонт',
    audience: 'Прораб и менеджер',
    difficulty: 'quick',
    estimatedSetup: '8 минут',
    recommendedFor: 'Первичный просчет',
    tags: ['ремонт', 'квартира', 'отделка', 'смета'],
    outcomes: ['Площадь', 'Тип ремонта', 'Материалы'],
    visual: 'repair',
    type: 'repair',
    basePrice: 30000,
    minPrice: 50000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('area', 'Площадь, м²', 3800),
      selectField('level', 'Тип ремонта', [
        { label: 'Эконом', value: 0, description: 'Базовый вариант' },
        { label: 'Капитальный', value: 45000, description: 'Полный цикл работ' },
        { label: 'Дизайнерский', value: 95000, description: 'Премиальная отделка' },
      ]),
      checkboxField('materials', 'Материалы включены', 22000),
    ],
  },
  {
    id: 'repair-turnkey',
    title: 'Ремонт под ключ',
    description:
      'Более детальная версия сметы с санузлами, уровнем отделки и закупкой материалов подрядчиком.',
    usesCount: 97,
    category: 'construction',
    industry: 'Ремонт под ключ',
    audience: 'Проектный отдел',
    difficulty: 'medium',
    estimatedSetup: '12 минут',
    recommendedFor: 'Квалификация больших объектов',
    tags: ['ремонт под ключ', 'санузлы', 'материалы'],
    outcomes: ['Санузлы', 'Чистовая', 'Материалы'],
    visual: 'repair',
    type: 'repair',
    basePrice: 40000,
    minPrice: 65000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('area', 'Площадь, м²', 4600),
      selectField('finishLevel', 'Уровень отделки', [
        { label: 'Черновая', value: 0, description: 'Подготовка под дальнейшие работы' },
        { label: 'Чистовая', value: 38000, description: 'Готовое жилое пространство' },
        { label: 'Дизайн-ремонт', value: 86000, description: 'Индивидуальные решения и декор' },
      ]),
      numberField('bathrooms', 'Санузлы, шт', 18500, false),
      checkboxField('materials', 'Закупка материалов подрядчиком', 26000),
    ],
  },
  {
    id: 'windows-balcony',
    title: 'Окна и остекление балконов',
    description:
      'Шаблон для оконных компаний: размеры, профиль, монтаж и теплый пакет. Удобен для рекламы в локальных сообществах.',
    usesCount: 89,
    category: 'services',
    industry: 'Окна',
    audience: 'Менеджер по замерам',
    difficulty: 'quick',
    estimatedSetup: '7 минут',
    recommendedFor: 'Реклама на холодный трафик',
    tags: ['окна', 'балкон', 'остекление', 'монтаж'],
    outcomes: ['Размер', 'Профиль', 'Монтаж'],
    visual: 'windows',
    type: 'services',
    basePrice: 2500,
    minPrice: 8000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('windowWidth', 'Ширина, см', 40),
      numberField('windowHeight', 'Высота, см', 45),
      selectField('profile', 'Профиль', [
        { label: 'Эконом', value: 0, description: 'Стандартная комплектация' },
        { label: 'Теплый', value: 6500, description: 'Улучшенная теплоизоляция' },
        { label: 'Премиум', value: 12000, description: 'Максимальный комфорт' },
      ]),
      checkboxField('installation', 'Монтаж включен', 8500),
    ],
  },
  {
    id: 'custom-kitchen',
    title: 'Кухни на заказ',
    description:
      'Расчет по длине, фасадам, столешнице и встройке. Хорошо работает как вход в диалог с дизайнером кухни.',
    usesCount: 104,
    category: 'business',
    industry: 'Кухни',
    audience: 'Дизайнер кухни',
    difficulty: 'medium',
    estimatedSetup: '11 минут',
    recommendedFor: 'Лидогенерация в премиум-сегменте',
    tags: ['кухни', 'фасады', 'столешница', 'встройка'],
    outcomes: ['Фасады', 'Столешница', 'Техника'],
    visual: 'kitchen',
    type: 'goods',
    basePrice: 45000,
    minPrice: 70000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('length', 'Длина кухни, м', 18000),
      selectField('facade', 'Фасады', [
        { label: 'ЛДСП', value: 0, description: 'Практичный базовый комплект' },
        { label: 'МДФ эмаль', value: 24000, description: 'Гладкие цветные фасады' },
        { label: 'Шпон / массив', value: 46000, description: 'Премиум-сегмент' },
      ]),
      selectField('countertop', 'Столешница', [
        { label: 'Пластик', value: 0, description: 'Стандартное решение' },
        { label: 'Акрил', value: 18000, description: 'Бесшовный современный вид' },
        { label: 'Кварц', value: 39000, description: 'Максимальная износостойкость' },
      ]),
      checkboxField('appliances', 'Встроенная техника', 32000),
    ],
  },
  {
    id: 'wardrobe-furniture',
    title: 'Шкафы и корпусная мебель',
    description:
      'Под заказные шкафы, гардеробные и корпусную мебель. Простая логика и хороший набор допродаж.',
    usesCount: 76,
    category: 'business',
    industry: 'Мебель',
    audience: 'Мебельный салон',
    difficulty: 'quick',
    estimatedSetup: '8 минут',
    recommendedFor: 'Сбор заявок из диалога',
    tags: ['шкаф', 'гардеробная', 'корпусная мебель'],
    outcomes: ['Модули', 'Материал', 'Фурнитура'],
    visual: 'furniture',
    type: 'goods',
    basePrice: 16000,
    minPrice: 28000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('modules', 'Модулей, шт', 4200),
      numberField('height', 'Высота, см', 95),
      selectField('material', 'Материал', [
        { label: 'ЛДСП', value: 0, description: 'Базовый материал' },
        { label: 'МДФ', value: 9500, description: 'Более плотный и долговечный' },
        { label: 'Шпон', value: 22000, description: 'Премиальный внешний вид' },
      ]),
      checkboxField('fittings', 'Премиальная фурнитура', 7800),
    ],
  },
  {
    id: 'city-delivery',
    title: 'Городская доставка',
    description:
      'Под курьерку и малую логистику: расстояние, вес, срочность и подъем на этаж.',
    usesCount: 88,
    category: 'services',
    industry: 'Доставка',
    audience: 'Оператор логистики',
    difficulty: 'quick',
    estimatedSetup: '6 минут',
    recommendedFor: 'Автоматизация входящих заявок',
    tags: ['доставка', 'курьер', 'срочно', 'подъем'],
    outcomes: ['Километры', 'Срочность', 'Подъем'],
    visual: 'delivery',
    type: 'delivery',
    basePrice: 500,
    minPrice: 990,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('distance', 'Расстояние, км', 28),
      numberField('weight', 'Вес, кг', 10),
      selectField('urgency', 'Срочность', [
        { label: 'В течение дня', value: 0, description: 'Стандартная доставка' },
        { label: 'За 3 часа', value: 600, description: 'Повышенный приоритет' },
        { label: 'За 1 час', value: 1200, description: 'Максимально быстро' },
      ]),
      checkboxField('floorLift', 'Подъем на этаж', 450),
    ],
  },
  {
    id: 'cargo-moving',
    title: 'Грузчики и квартирный переезд',
    description:
      'Шаблон для компаний по переездам: этажность, часы, объем и упаковка. Хорошо квалифицирует сложные заявки.',
    usesCount: 63,
    category: 'services',
    industry: 'Переезды',
    audience: 'Диспетчер',
    difficulty: 'medium',
    estimatedSetup: '9 минут',
    recommendedFor: 'Снижение ручных уточнений',
    tags: ['переезд', 'грузчики', 'этаж', 'упаковка'],
    outcomes: ['Часы', 'Этаж', 'Упаковка'],
    visual: 'delivery',
    type: 'delivery',
    basePrice: 1800,
    minPrice: 3900,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('hours', 'Часы работы', 1600),
      numberField('loaders', 'Грузчиков, чел', 900),
      numberField('floors', 'Этажей без лифта', 250, false),
      checkboxField('packing', 'Упаковка и стрейч', 2800),
    ],
  },
  {
    id: 'cleaning-post-renovation',
    title: 'Клининг после ремонта',
    description:
      'Нишевый шаблон для дорогих уборок: площадь, окна, санузлы и сложные зоны. Отлично подходит под таргет на новоселов.',
    usesCount: 91,
    category: 'services',
    industry: 'Клининг',
    audience: 'Оператор клининга',
    difficulty: 'quick',
    estimatedSetup: '7 минут',
    recommendedFor: 'Высокий средний чек',
    tags: ['клининг', 'после ремонта', 'окна', 'санузел'],
    outcomes: ['Площадь', 'Окна', 'Санузлы'],
    visual: 'cleaning',
    type: 'services',
    basePrice: 1800,
    minPrice: 3500,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('area', 'Площадь, м²', 120),
      selectField('cleaningType', 'Тип уборки', [
        { label: 'Поддерживающая', value: 0, description: 'Быстрый регулярный выезд' },
        { label: 'Генеральная', value: 2800, description: 'Глубокая уборка всей квартиры' },
        { label: 'После ремонта', value: 5400, description: 'Сбор пыли и строительных следов' },
      ]),
      numberField('bathrooms', 'Санузлы, шт', 950, false),
      checkboxField('windowsWash', 'Мытье окон', 2400),
      checkboxField('fridge', 'Чистка кухни и техники', 1600),
    ],
  },
  {
    id: 'detailing',
    title: 'Автодетейлинг',
    description:
      'Для детейлинг-студий: кузов, салон, покрытие и антидождь. Ниша с хорошим апсейлом и понятными пакетами.',
    usesCount: 57,
    category: 'services',
    industry: 'Автоуслуги',
    audience: 'Администратор студии',
    difficulty: 'medium',
    estimatedSetup: '9 минут',
    recommendedFor: 'Апсейл пакетов',
    tags: ['детейлинг', 'полировка', 'керамика', 'салон'],
    outcomes: ['Кузов', 'Покрытие', 'Салон'],
    visual: 'auto',
    type: 'services',
    basePrice: 2900,
    minPrice: 6900,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      selectField('carClass', 'Класс авто', [
        { label: 'Седан', value: 0, description: 'Базовая ставка' },
        { label: 'Кроссовер', value: 2200, description: 'Больше площадь кузова' },
        { label: 'Премиум SUV', value: 4800, description: 'Сложный кузов и объем салона' },
      ]),
      selectField('servicePack', 'Пакет работ', [
        { label: 'Химчистка салона', value: 5200, description: 'Глубокая очистка салона' },
        { label: 'Полировка', value: 7400, description: 'Восстановление блеска' },
        { label: 'Керамика', value: 12800, description: 'Защитное покрытие' },
      ]),
      checkboxField('antiRain', 'Антидождь на стекла', 1900),
      checkboxField('engineBay', 'Мойка подкапотного пространства', 2400),
    ],
  },
  {
    id: 'laser-epilation',
    title: 'Лазерная эпиляция',
    description:
      'Под салоны и клиники эстетики: зоны, количество процедур и абонемент. Ниша с понятным циклом продаж.',
    usesCount: 64,
    category: 'services',
    industry: 'Бьюти',
    audience: 'Администратор салона',
    difficulty: 'quick',
    estimatedSetup: '7 минут',
    recommendedFor: 'Продажа абонементов',
    tags: ['эпиляция', 'бьюти', 'абонемент', 'зоны'],
    outcomes: ['Зоны', 'Курс', 'Абонемент'],
    visual: 'beauty',
    type: 'services',
    basePrice: 900,
    minPrice: 2500,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      selectField('zone', 'Основная зона', [
        { label: 'Подмышки', value: 0, description: 'Быстрый визит' },
        { label: 'Глубокое бикини', value: 1600, description: 'Самая частая услуга' },
        { label: 'Ноги полностью', value: 3600, description: 'Большая зона' },
      ]),
      numberField('sessions', 'Процедур в курсе', 450),
      checkboxField('consultation', 'Первичная консультация врача', 1200),
      checkboxField('subscription', 'Оформить абонемент', -1500),
    ],
  },
  {
    id: 'bankruptcy-law',
    title: 'Банкротство физлиц',
    description:
      'Калькулятор для юридической ниши: долг, кредиторы, имущество и сопровождение. Удобен как прогревающий квиз перед консультацией.',
    usesCount: 52,
    category: 'business',
    industry: 'Юридические услуги',
    audience: 'Юрист и колл-центр',
    difficulty: 'advanced',
    estimatedSetup: '14 минут',
    recommendedFor: 'Теплый лид перед звонком',
    tags: ['банкротство', 'юрист', 'долги', 'кредиторы'],
    outcomes: ['Сумма долга', 'Кредиторы', 'Сопровождение'],
    visual: 'legal',
    type: 'services',
    basePrice: 15000,
    minPrice: 45000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('debt', 'Сумма долга, ₽', 0),
      numberField('creditors', 'Количество кредиторов', 2400),
      selectField('caseComplexity', 'Сложность дела', [
        { label: 'Стандартная', value: 0, description: 'Типовой пакет документов' },
        { label: 'С имуществом', value: 18000, description: 'Нужно сопровождение по активам' },
        { label: 'Со спорами', value: 32000, description: 'Повышенная сложность' },
      ]),
      checkboxField('fullSupport', 'Полное сопровождение под ключ', 26000),
    ],
  },
  {
    id: 'mortgage',
    title: 'Ипотечный калькулятор',
    description:
      'Расчет ежемесячного платежа по сумме, ставке и сроку. Полезен агентствам недвижимости и ипотечным брокерам.',
    usesCount: 73,
    category: 'finance',
    industry: 'Ипотека',
    audience: 'Брокер и риелтор',
    difficulty: 'medium',
    estimatedSetup: '8 минут',
    recommendedFor: 'Прогрев клиента до звонка',
    tags: ['ипотека', 'ежемесячный платеж', 'недвижимость'],
    outcomes: ['Сумма', 'Ставка', 'Срок'],
    visual: 'mortgage',
    type: 'custom',
    basePrice: 0,
    minPrice: 0,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'custom',
    customFormula:
      '(loanAmount + loanAmount * (interestRate / 100) * loanYears) / (loanYears * 12)',
    fields: [
      numberField('loanAmount', 'Сумма кредита', 0),
      numberField('interestRate', 'Ставка, %', 0),
      numberField('loanYears', 'Срок, лет', 0),
    ],
  },
  {
    id: 'credit',
    title: 'Потребительский кредит',
    description:
      'Удобный шаблон для расчета ежемесячного платежа, который можно использовать в лендингах и VK-воронках.',
    usesCount: 58,
    category: 'finance',
    industry: 'Кредитование',
    audience: 'Финансовый консультант',
    difficulty: 'medium',
    estimatedSetup: '8 минут',
    recommendedFor: 'Сбор горячих обращений',
    tags: ['кредит', 'платеж', 'финансы'],
    outcomes: ['Сумма', 'Процент', 'Срок'],
    visual: 'credit',
    type: 'custom',
    basePrice: 0,
    minPrice: 0,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'custom',
    customFormula: '(creditAmount + creditAmount * (creditRate / 100)) / creditMonths',
    fields: [
      numberField('creditAmount', 'Сумма кредита', 0),
      numberField('creditRate', 'Процентная ставка, %', 0),
      numberField('creditMonths', 'Срок, месяцев', 0),
    ],
  },
  {
    id: 'course-pricing',
    title: 'Онлайн-курс и наставничество',
    description:
      'Под образовательные продукты: тариф, куратор, доступ к модулям и личные разборы. Удобно продавать через сообщения сообщества.',
    usesCount: 49,
    category: 'business',
    industry: 'Онлайн-образование',
    audience: 'Продюсер и менеджер',
    difficulty: 'quick',
    estimatedSetup: '7 минут',
    recommendedFor: 'Сравнение тарифов',
    tags: ['курс', 'обучение', 'наставничество', 'тарифы'],
    outcomes: ['Тариф', 'Куратор', 'Разборы'],
    visual: 'education',
    type: 'services',
    basePrice: 4900,
    minPrice: 4900,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      selectField('tariff', 'Тариф', [
        { label: 'Базовый', value: 0, description: 'Только уроки и чат' },
        { label: 'С куратором', value: 12000, description: 'Проверка домашних заданий' },
        { label: 'VIP', value: 28000, description: 'Личные созвоны и разборы' },
      ]),
      numberField('modules', 'Дополнительных модулей', 1800, false),
      checkboxField('mentor', 'Личная консультация', 6500),
      checkboxField('certificate', 'Итоговая аттестация и сертификат', 2200),
    ],
  },
  {
    id: 'event-catering',
    title: 'Кейтеринг на мероприятие',
    description:
      'Хороший шаблон для ивент-рынка: гости, формат, меню и сервис. Помогает быстро считать корпоративы и свадьбы.',
    usesCount: 41,
    category: 'business',
    industry: 'Ивенты',
    audience: 'Менеджер площадки',
    difficulty: 'medium',
    estimatedSetup: '10 минут',
    recommendedFor: 'Корпоративные заявки',
    tags: ['кейтеринг', 'мероприятие', 'банкет', 'гости'],
    outcomes: ['Гости', 'Формат', 'Сервис'],
    visual: 'events',
    type: 'services',
    basePrice: 15000,
    minPrice: 30000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('guests', 'Количество гостей', 1400),
      selectField('format', 'Формат', [
        { label: 'Фуршет', value: 0, description: 'Легкий формат' },
        { label: 'Банкет', value: 22000, description: 'Полная подача и обслуживание' },
        { label: 'Свадьба', value: 46000, description: 'Расширенный сервис и координация' },
      ]),
      checkboxField('staff', 'Дополнительный персонал', 9800),
      checkboxField('decor', 'Базовый декор и сервировка', 12500),
    ],
  },
  {
    id: 'security-systems',
    title: 'Видеонаблюдение и сигнализация',
    description:
      'Для интеграторов безопасности: точки, камеры, монтаж и сервер хранения. Сценарий подходит B2B и частным клиентам.',
    usesCount: 46,
    category: 'services',
    industry: 'Безопасность',
    audience: 'Инженер и менеджер',
    difficulty: 'advanced',
    estimatedSetup: '13 минут',
    recommendedFor: 'Квалификация объектов',
    tags: ['видеонаблюдение', 'сигнализация', 'монтаж', 'сервер'],
    outcomes: ['Камеры', 'Монтаж', 'Хранение'],
    visual: 'security',
    type: 'services',
    basePrice: 12000,
    minPrice: 35000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('cameras', 'Камер, шт', 4200),
      selectField('cameraType', 'Тип камер', [
        { label: 'Внутренние', value: 0, description: 'Для офиса или магазина' },
        { label: 'Уличные', value: 6800, description: 'Защита от влаги и мороза' },
        { label: 'Поворотные PTZ', value: 14500, description: 'Для больших площадей' },
      ]),
      checkboxField('installation', 'Монтаж и пусконаладка', 18000),
      checkboxField('storage', 'Сервер хранения архива', 26000),
    ],
  },
  {
    id: 'septic-install',
    title: 'Септики и автономная канализация',
    description:
      'Нишевая стройка для загородки: пользователи, грунт, выезд техники и монтаж под ключ.',
    usesCount: 39,
    category: 'construction',
    industry: 'Септики',
    audience: 'Инженер замера',
    difficulty: 'advanced',
    estimatedSetup: '14 минут',
    recommendedFor: 'Загородные объекты',
    tags: ['септик', 'канализация', 'грунт', 'монтаж'],
    outcomes: ['Пользователи', 'Грунт', 'Техника'],
    visual: 'septic',
    type: 'construction',
    basePrice: 35000,
    minPrice: 95000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('residents', 'Количество пользователей', 7200),
      selectField('soil', 'Тип грунта', [
        { label: 'Песок', value: 0, description: 'Базовый монтаж' },
        { label: 'Суглинок', value: 12000, description: 'Усложненная подготовка' },
        { label: 'Высокие грунтовые воды', value: 28000, description: 'Нужны доп. работы' },
      ]),
      checkboxField('excavator', 'Привлечение спецтехники', 18500),
      checkboxField('turnkey', 'Монтаж под ключ', 34000),
    ],
  },
  {
    id: 'well-drilling',
    title: 'Бурение скважин',
    description:
      'Подрядный расчет глубины, обсадки, насоса и обустройства. Отличная ниша для сезонной рекламы в поселках.',
    usesCount: 34,
    category: 'construction',
    industry: 'Бурение',
    audience: 'Замерщик и сметчик',
    difficulty: 'advanced',
    estimatedSetup: '15 минут',
    recommendedFor: 'Сезонный спрос',
    tags: ['скважина', 'бурение', 'обсадка', 'насос'],
    outcomes: ['Глубина', 'Обсадка', 'Насос'],
    visual: 'septic',
    type: 'construction',
    basePrice: 25000,
    minPrice: 70000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('depth', 'Глубина, м', 2300),
      selectField('casing', 'Тип обсадки', [
        { label: 'Пластик', value: 0, description: 'Базовое решение' },
        { label: 'Сталь', value: 18000, description: 'Для сложных грунтов' },
        { label: 'Комбинированная', value: 32000, description: 'Надежный дорогой вариант' },
      ]),
      checkboxField('pump', 'Погружной насос', 22000),
      checkboxField('arrangement', 'Обустройство устья', 18000),
    ],
  },
  {
    id: 'fence-install',
    title: 'Заборы и ворота',
    description:
      'Для подрядчиков по участкам: погонные метры, материал, калитка и откатные ворота.',
    usesCount: 44,
    category: 'construction',
    industry: 'Заборы',
    audience: 'Отдел продаж',
    difficulty: 'quick',
    estimatedSetup: '8 минут',
    recommendedFor: 'Локальная реклама поселков',
    tags: ['забор', 'ворота', 'калитка', 'профлист'],
    outcomes: ['Метры', 'Материал', 'Ворота'],
    visual: 'fence',
    type: 'construction',
    basePrice: 12000,
    minPrice: 28000,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('meters', 'Длина забора, м', 1800),
      selectField('material', 'Материал', [
        { label: 'Профлист', value: 0, description: 'Практичный базовый вариант' },
        { label: 'Штакетник', value: 16000, description: 'Более аккуратный вид' },
        { label: 'Жалюзи', value: 42000, description: 'Премиум-сегмент' },
      ]),
      checkboxField('wicket', 'Калитка', 8500),
      checkboxField('gate', 'Откатные ворота', 68000),
    ],
  },
  {
    id: 'tow-truck',
    title: 'Эвакуатор и техпомощь',
    description:
      'Шаблон для автониши: расстояние, масса, срочность и сложность погрузки.',
    usesCount: 37,
    category: 'services',
    industry: 'Эвакуация',
    audience: 'Диспетчер 24/7',
    difficulty: 'quick',
    estimatedSetup: '6 минут',
    recommendedFor: 'Ночные и срочные заявки',
    tags: ['эвакуатор', 'авто', 'техпомощь', 'срочно'],
    outcomes: ['Км', 'Масса', 'Сложность'],
    visual: 'auto',
    type: 'delivery',
    basePrice: 1800,
    minPrice: 3500,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      numberField('distance', 'Расстояние, км', 45),
      selectField('vehicleType', 'Тип транспорта', [
        { label: 'Легковой', value: 0, description: 'Стандартный тариф' },
        { label: 'Кроссовер', value: 1200, description: 'Выше масса и габариты' },
        { label: 'Коммерческий', value: 3600, description: 'Сложная погрузка' },
      ]),
      checkboxField('night', 'Ночной выезд', 2200),
      checkboxField('blocked', 'Заблокированные колеса / сложная погрузка', 3400),
    ],
  },
  {
    id: 'tattoo-removal',
    title: 'Удаление тату и перманента',
    description:
      'Специализированный шаблон под эстетические процедуры: размер зоны, плотность и количество сеансов.',
    usesCount: 28,
    category: 'services',
    industry: 'Эстетическая медицина',
    audience: 'Администратор клиники',
    difficulty: 'quick',
    estimatedSetup: '7 минут',
    recommendedFor: 'Прогрев дорогой услуги',
    tags: ['удаление тату', 'перманент', 'лазер'],
    outcomes: ['Размер', 'Плотность', 'Сеансы'],
    visual: 'beauty',
    type: 'services',
    basePrice: 1500,
    minPrice: 3500,
    globalCoefficient: 1,
    discount: 0,
    formulaMode: 'simple',
    customFormula: '',
    fields: [
      selectField('zoneSize', 'Размер зоны', [
        { label: 'До 5 см', value: 0, description: 'Локальная зона' },
        { label: 'До 10 см', value: 2200, description: 'Средний размер' },
        { label: 'Большая зона', value: 5800, description: 'Длинная работа' },
      ]),
      selectField('density', 'Плотность пигмента', [
        { label: 'Легкая', value: 0, description: 'Быстрая коррекция' },
        { label: 'Средняя', value: 1400, description: 'Стандартный кейс' },
        { label: 'Плотная', value: 3200, description: 'Требует больше проходов' },
      ]),
      numberField('sessions', 'Ожидаемо сеансов', 350),
      checkboxField('numbing', 'Анестезия', 900),
    ],
  },
];

export const createTemplateFromPreset = (
  presetId: string,
  folderId?: string,
): CalculatorTemplate | undefined => {
  const preset = templateCatalog.find((item) => item.id === presetId);
  if (!preset) {
    return undefined;
  }

  const now = new Date().toISOString();
  const id = createRandomId();

  return {
    id,
    folderId,
    title: preset.title,
    description: preset.description,
    requestForm: createDefaultRequestFormSettings(),
    publicationStatus: 'draft',
    publicId: createTemplatePublicId(id.slice(0, 8)),
    publishedAt: undefined,
    lastModifiedBy: 'Администратор',
    type: preset.type,
    basePrice: preset.basePrice,
    discount: preset.discount,
    minPrice: preset.minPrice,
    globalCoefficient: preset.globalCoefficient,
    formulaMode: preset.formulaMode,
    customFormula: preset.customFormula,
    createdAt: now,
    updatedAt: now,
    fields: preset.fields.map((field) => ({
      ...field,
      id: createRandomId(),
      options: field.options?.map((option) => ({
        ...option,
        id: createRandomId(),
      })),
    })),
  };
};
